// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fatrsjdttkioolbefanv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdHJzamR0dGtpb29sYmVmYW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDYyNDYsImV4cCI6MjA1OTYyMjI0Nn0.53N7IGAR7g0KjBShiB_6MIpLaHgFkAMgdWZuWk7otDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);